name: CD

env:
  AWS_REGION: eu-west-1

on:
  push:
    branches:
      - 'first-pr'
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy on AWS App Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          # download copilot
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.8.3/copilot-linux && \
          # make copilot bin executable
          chmod +x copilot-linux && \
          # move to path
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          # add to PATH
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Deplou on AWS App Runner
        run: copilot deploy -a demo-aws-app-runner -e lab -n app --tag lab-${GITHUB_SHA:0:7}
