name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run prettier
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        branch: [master, branch]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        if: matrix.branch == 'branch'

      - uses: actions/checkout@v3
        if: matrix.branch == 'master'
        with:
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run test
        run: |
          npm run test --maxWorkers=2 --coverage --testLocationInResults --json --outputFile=report-${{ matrix.branch }}.json

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-${{ matrix.branch }}
          path: report-${{ matrix.branch }}.json

  test-coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Download branch code coverage
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report-branch
          path: .

      - name: Download master codecoverage
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report-master
          path: .

      - name: Test and coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          working-directory: .
          coverage-file: ./report-branch.json
          base-coverage-file: ./report-master.json
